### PR TITLE
Additional confirmation for deletions

### LINKED ISSUE #64: When deleting things, display more information about it, prior to the confirmation
Currently when you delete a project there is a confirmation, but no additional information is presented to enable you to make this choice

```
$ lagoon delete project --project reports
Deleting reports
✔ Yes
Result: success
```

**Describe the solution you'd like**
Perhaps a simple confirmation message like:

```
$ lagoon delete project --project reports
You are attempting to delete project 'reports' ID 10665, with git URL 'git@github.com/blah.git', are you sure?
```

**Additional context**
The idea here is to prevent people from deleting the wrong thing.

### LINKED ISSUE #99: Deleting a user should have a yes/no selection
**Is your feature request related to a problem? Please describe.**
Deleting a user with `lagoon delete user -E root@example.com` deletes the user right away without any reconfirmation.

**Describe the solution you'd like**
Deleting a user should also have a yes/no possibility

### PR DESCRIPTION
**Pull request by shreddedbacon**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [x] Changelog entry has been written

Display more confirmation information when deleting resources from a Lagoon

# Changelog Entry

Improvement - More verbose deletion confirmations

# Closing issues
closes #99

### CODE REVIEW

**Comment by tobybellwood** [comment]
woohoo 💯

**Comment by shreddedbacon** [comment]
#64 mentions to display even more information, some of that information is only available if we run an initial query, this could add additional time to requests, as it would require running a discovery query to make sure it exists first.

Happy to implement this though if it would be more helpful

**Comment by seanhamlin** [comment]
Yeah, that was my original intent, was to provide more information about what you are going to do, prior to just doing it. A read query makes perfect sense. Having the git URL for instance for project deletions is a good way to ensure you are doing the right thing.

**Comment by shreddedbacon** [comment]
Will merge this for now, but will look to add the additional sanity checks for #64

**Pull request merged**
