### PR TITLE
Import / export

### LINKED ISSUE #36: Onboarding
**Is your feature request related to a problem? Please describe.**
When onboarding customers or projects, it would be good to be able to provide a file that describes how the customer/project should be configured

**Describe the solution you'd like**
I think something like this might work well
```
groups:
  - name: example-com
users:
  - user:
      email: usera@example.com
      sshkey: ~/usera.pub
    groups:
      - name: example-com
        role: owner
  - user:
      email: userb@example.com
      sshkey: ~/userb.pub
    groups:
      - name: example-com
        role: developer
projects:
  - name: example-com
    giturl: git@github.com:example/example-com.git
    openshift: 2
    branches: "master|develop|staging"
    productionenvironment: master
    groups:
      - example-com
```
Then a `lagoon import -I /path/to/file` would start it off

### PR DESCRIPTION
**Pull request by smlx**
# TODO
- [x] Fix notifications not being added to projects
- [x] Correctly handle (and differentiate between) Billing Groups and regular Groups.
- [x] Allow export of project private keys (default disabled).
- [x] Unhide `import`/`export`.

# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [x] Changelog entry has been written

This PR adds functionality for import and export of projects from and to lagoon:

* Projects are exported to YAML.
* All parts of a project including notifications, groups, users, environments, and env-vars (for both project and environment) are exported.
* Notifications, groups and users can be excluded from the export, although the references to these will remain (so they must exist in the destination lagoon).
* `auto-idle` on environments is _not_ handled due to it not being an attribute of Lagoon's AddEnvironmentInput`. `auto-idle` on projects is handled correctly.
* OpenshiftID is not exported and must be provided on the command-line on `import`.
* Project private keys are not exported. Imported projects will have auto-generated keys instead.
* Only import/export of individual projects is currently implemented (i.e. not all projects) because that's what I need right now :-P

This PR is a draft because it required some changes to the existing Lagoon API schema structs for ease of config YAML (un)marshaling. I've re-implemented these in the `schema` package to avoid breaking existing functionality. It still refers to the existing `api` package for enums.

This PR also has some other experimental changes that might need discussion:

* Packages are placed in `internal/` to avoid exporting unstable APIs.
* The `lagoon` package implements a high-level API for operations against a Lagoon instance and uses dependency injection to ease testing.
* `client` re-implements the Lagoon client functionality to take advantage of the built-in unmarshalling functionality of `machinebox/graphql`.
* Generates embedded files, to separate query templates and and code.
* Generates interface mocks for testing.
* Uses the `E` variant of the `cobra.Command` struct's attributes to simplify error handling (`RunE` etc.).

The idea with these experimental changes is that if they seem like an improvement we can gradually migrate functionality across. Or not, if they don't :D

This has got some light unit test coverage, and I've done quite a bit of manual testing. I plan to use this branch to do some migrations in the next week or so which will help prove out the functionality, but I wanted to give the opportunity for feedback on the approach and the experiental bits in the
meantime :-)

This PR incorporates the changes from #83, #84, and #85. I've just split those out separately for ease of review.

# Changelog Entry
Feature - Import/Export (#36)

# Closing issues
Closes #36

### CODE REVIEW

**Comment by shreddedbacon** [comment]
This looks great so far.

I'll have a look at it in more depth to make sure I understand everything that proposed.

**Comment by seanhamlin** [comment]
I just gave this a whirl, exporting a project from CH1 to k8s. 

Things I liked:
* Able to specify the OpenShiftID upon import (even though there is no OpenShift in this case)
* I was able to clean up the YAML prior to import
* All environment variables imported correctly, even the ones with special characters

I would change:
* Remove the `--environment` option from export, as it is ignored and all environments are exported

**Comment by smlx** [comment]
> I just gave this a whirl, exporting a project from CH1 to k8s.

Great, thanks!

> Things I liked:
>     * Able to specify the OpenShiftID upon import (even though there is no OpenShift in this case)
>     * I was able to clean up the YAML prior to import
>     * All environment variables imported correctly, even the ones with special characters

:sunglasses:  

> Things I had to do manually:
>     * Copy the project SSH key across (I don't have admin access to the Git repo to add another deploy key)

Seems like this option would only be useful for testing because you've still got to set up the webhooks on the repo in which case you'd also have enough access to add a deploy key.
Maybe it should disabled by default but optionally enabled?

>    * Alter the `active_systems_deploy`, `active_systems_remove`, `active_systems_task` to be k8s specific

Those options should probably just be set to the correct value by lagoon based on the targeted cluster. What happens at the moment if you don't set them explicitly on import for a k8s cluster? Does it set them to the (wrong) openshift values?

> I would change:
>     * Remove the `--environment` option from export, as it is ignored and all environments are exported

This is a global option so it can't be removed even if a command doesn't use it. I'd also love to clean up the CLI structure to avoid these redundant options, but not in this PR.

> Unsure about:
>     * Why the `import` and `export` commands are not in the list screens?

Not sure what you mean here.. could you elaborate? Do you mean `lagoon help`?

**Comment by seanhamlin** [comment]
> > Things I had to do manually:
> > * Copy the project SSH key across (I don't have admin access to the Git repo to add another deploy key)
> 
> Seems like this option would only be useful for testing because you've still got to set up the webhooks on the repo in which case you'd also have enough access to add a deploy key.
> Maybe it should disabled by default but optionally enabled?

Yeah, I think an option to copy the private key would be ideal, as this way you have 1 less step to do.

> 
> > * Alter the `active_systems_deploy`, `active_systems_remove`, `active_systems_task` to be k8s specific
> 
> Those options should probably just be set to the correct value by lagoon based on the targeted cluster. What happens at the moment if you don't set them explicitly on import for a k8s cluster? Does it set them to the (wrong) openshift values?

Correct, they default to OpenShift specific tasks. Sounds like a Lagoon feature here.

> 
> > I would change:
> > * Remove the `--environment` option from export, as it is ignored and all environments are exported
> 
> This is a global option so it can't be removed even if a command doesn't use it. I'd also love to clean up the CLI structure to avoid these redundant options, but not in this PR.

Sounds like a new issue is needed

> 
> > Unsure about:
> > * Why the `import` and `export` commands are not in the list screens?
> 
> Not sure what you mean here.. could you elaborate? Do you mean `lagoon help`?

Yes.

```
$ go run main.go -l k8s help | grep -i import
```

**Comment by shreddedbacon** [comment]
So the export/import that I originally wrote exported the project key, and could also import the key. I don't see why this couldn't also support that feature. It would mean not having to have anyone re-add any new public keys to their repositories or anything.

**Comment by smlx** [comment]
Thanks for creating the new issues @seanhamlin!

Re: private keys, I agree that since the Lagoon API supports export of the private key material it makes sense to add the option here too.

The reason that I didn't add key export initially is that:

* I didn't need it for the migration I'm working on since we're encouraging the customer to generate new keys per project.
* IMO it's not great security-wise that the Lagoon API lets you pull the private key material at all.

On the last point, I think it would be better if you could _add_ private key material but then only _retrieve_ the fingerprint afterwards. I've been meaning to create a Lagoon issue for this..

**Comment by shreddedbacon** [comment]
As I'm also going to need this functionality soon, so I had a skim over the PR and the proposed changes. Works as intended, but I'll do some more functional testing with it tomorrow for my particular use case to see if anything is missing.

Overall, I'm happy with the proposed changes. I'm thinking it would be good to bring the rest of the CLI in line with these changes over a period of time so we can start doing better tests.

@smlx When do you think you will have this PR ready for review?

**Comment by smlx** [comment]
@shreddedbacon  I'll try to finish it off in the next 48 hours.. basically the bits I've identified as missing are in the TODO list at the top of the PR. It would be great for you to test this too -  there are probably some more rough edges I've missed.

**Comment by smlx** [comment]
That was a long 48 hours :cry: 

I've updated this and it's ready for review.

Since the last review I've added:
- handling for groups/billinggroups
- handling for new notification types
- ability to export project private keys (off by default)
- unhide import/export commands in `lagoon help`

An important change that the notification and billinggroup handling introduces is the concept of lagoon versions. This is added as a field in `.lagoon.yml`. e.g. see the last line here:
```
  local:
    graphql: http://localhost:3000/graphql
    hostname: localhost
    port: "2020"
    token: <snip>
    ui: http://localhost:8888
    version: 1.2.0
```

By default (if version field is not defined) it will fall back to the simplest request type for compatibility. So if you want to export billinggroups or email/teams notifications you'll have to set the version to `1.2.0` or higher.

**Pull request merged**
