### PR TITLE
Added support for CONTAINER_REGISTRY and INTERNAL_CONTAINER_REGISTRY

### LINKED ISSUE #150: Add support for CONTAINER_REGISTRY and INTERNAL_CONTAINER_REGISTRY scope
**Describe the bug**
`lagoon add variable -S CONTAINER_REGISTRY` or `lagoon add variable -S INTERNAL_CONTAINER_REGISTRY` commands fail with error:
```Error: Unknown scope: CONTAINER_REGISTRY```

**To Reproduce**
1. Try to add a variable with scope `CONTAINER_REGISTRY` or `INTERNAL_CONTAINER_REGISTRY`
2. See error

**Expected behavior**
The expected result should be variable added successfully

### PR DESCRIPTION
**Pull request by vincenzodnp**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [x] Documentation has been written/updated.
- [x] Changelog entry has been written

This PR add the support for `CONTAINER_REGISTRY` and `INTERNAL_CONTAINER_REGISTRY` scopes to add variable command.

# Changelog Entry
Improvement - CONTAINER_REGISTRY and INTERNAL_CONTAINER_REGISTRY scopes support (#150)

# Closing issues
closes #150

### CODE REVIEW

**Review by shreddedbacon — APPROVED** [review]

**Comment by shreddedbacon** [comment]
Going to merge this, but flagging it as something that should be done differently in the future

**Comment by AlexSkrypnyk** [comment]
@vincenzodnp @shreddedbacon  could you please confirm that this would also allow to retrieve the existing variables in `CONTAINER_REGISTRY` scope with `lagoon list variables`

**Comment by shreddedbacon** [comment]
> @vincenzodnp @shreddedbacon could you please confirm that this would also allow to retrieve the existing variables in `CONTAINER_REGISTRY` scope with `lagoon list variables`

Yes, scope doesn't matter when listing variables.

**Comment by shreddedbacon** [comment]
@AlexSkrypnyk I will aim to release this shortly for you.

**Pull request merged**
